spring:
  application:
    name: backend
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true  #pretty sql
    hibernate:
      use-new-id-generator-mappings: false
      #      ddl-auto: create
      #      ddl-auto: update
      ddl-auto: none
  datasource:
    hikari:
    driver-class-name:
    jdbc-url:
    username:
    password:

jwt:
  secret: test
  expiration-sec: 7776000

server:
  port: 8080
