spring:
  application:
    name: backend
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true  #pretty sql
    hibernate:
      use-new-id-generator-mappings: false
      #      ddl-auto: create
      #      ddl-auto: update
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: qwer!234

jwt:
  secret: test
  expiration-sec: 7776000

server:
  port: 80
